require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');

const watsonxService = require('./watsonx');
const dockerService = require('./docker');
const filesService = require('./files');

const app = express();
app.use(cors());
app.use(express.json());
app.use(express.static(path.join(__dirname, '..', '..', 'public')));

// In-memory storage for project status
const projects = new Map();

// Generate service endpoint
app.post('/api/generate', async (req, res) => {
  const { idea, projectName } = req.body;
  
  if (!idea || !projectName) {
    return res.status(400).json({ 
      success: false, 
      error: 'Missing required fields: idea and projectName' 
    });
  }
  
  const projectId = `proj_${Date.now()}`;
  
  projects.set(projectId, {
    status: 'generating',
    progress: 0,
    logs: [],
    idea,
    projectName
  });
  
  // Start generation in background
  generateService(projectId, idea, projectName);
  
  res.json({ success: true, projectId, status: 'generating' });
});

// Check status endpoint
app.get('/api/status/:projectId', (req, res) => {
  const project = projects.get(req.params.projectId);
  
  if (!project) {
    return res.status(404).json({ status: 'not_found' });
  }
  
  res.json(project);
});

// Stop service endpoint
app.delete('/api/projects/:projectId', async (req, res) => {
  const projectId = req.params.projectId;
  const project = projects.get(projectId);
  
  if (!project) {
    return res.status(404).json({ success: false, error: 'Project not found' });
  }
  
  try {
    await dockerService.stop(projectId);
    await filesService.deleteProject(projectId);
    projects.delete(projectId);
    
    res.json({ success: true, message: 'Service stopped and cleaned up' });
  } catch (error) {
    res.status(500).json({ success: false, error: error.message });
  }
});

// Health check endpoint
app.get('/api/health', (req, res) => {
  res.json({ status: 'healthy', timestamp: new Date().toISOString() });
});

// Main generation flow
async function generateService(projectId, idea, projectName) {
  const project = projects.get(projectId);
  
  try {
    // Step 1: Call watsonx.ai
    project.logs.push('→ Calling IBM watsonx.ai (Granite model)...');
    project.progress = 10;
    
    let generated;
    try {
      generated = await watsonxService.generateGoService(idea, projectName);
      project.logs.push('✓ Code generated by watsonx.ai');
    } catch (error) {
      project.logs.push('⚠ watsonx.ai unavailable, using fallback template');
      generated = watsonxService.generateFromTemplate(idea, projectName);
    }
    
    // Step 2: Write files
    project.logs.push('→ Writing files to disk...');
    project.progress = 30;
    const projectPath = await filesService.writeFiles(projectId, generated.files);
    project.logs.push(`✓ Files written to ${projectPath}`);
    
    // Step 3: Build Docker image
    project.logs.push('→ Building Docker image...');
    project.progress = 50;
    const dockerResult = await dockerService.buildAndRun(projectId, projectPath);
    project.logs.push('✓ Docker image built successfully');
    
    // Step 4: Container started
    project.logs.push('→ Starting container...');
    project.progress = 80;
    project.logs.push('✓ Container started and healthy');
    
    // Step 5: Done
    project.status = 'running';
    project.progress = 100;
    project.previewUrl = dockerResult.previewUrl;
    project.endpoints = generated.endpoints || ['GET /health - Health check'];
    project.logs.push('🎉 Service is ready!');
    
  } catch (error) {
    project.status = 'error';
    project.error = error.message;
    project.logs.push(`✗ Error: ${error.message}`);
    console.error(`Generation failed for ${projectId}:`, error);
    
    // Cleanup on error
    try {
      await dockerService.cleanup(projectId);
      await filesService.deleteProject(projectId);
    } catch (cleanupError) {
      console.error('Cleanup failed:', cleanupError);
    }
  }
}

// Start server
const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`🚀 AI Developer Assistant Backend running on port ${PORT}`);
  console.log(`📝 API endpoints:`);
  console.log(`   POST   http://localhost:${PORT}/api/generate`);
  console.log(`   GET    http://localhost:${PORT}/api/status/:projectId`);
  console.log(`   DELETE http://localhost:${PORT}/api/projects/:projectId`);
  console.log(`   GET    http://localhost:${PORT}/api/health`);
  console.log(`\n💡 Make sure to configure .env file with watsonx.ai credentials`);
});

// Graceful shutdown
process.on('SIGINT', async () => {
  console.log('\n🛑 Shutting down gracefully...');
  
  // Stop all running containers
  for (const [projectId, project] of projects.entries()) {
    if (project.status === 'running') {
      try {
        await dockerService.stop(projectId);
        console.log(`✓ Stopped ${projectId}`);
      } catch (error) {
        console.error(`Failed to stop ${projectId}:`, error.message);
      }
    }
  }
  
  process.exit(0);
});

// Made with Bob
